=== madiantech/tkcore/CoreWebTest/TestWeb/Xml/schema/v5/CodeData.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Chen Jiangyong (Baison) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tk="http://www.qdocuments.net" targetNamespace="http://www.qdocuments.net" elementFormDefault="qualified">
  <xs:include schemaLocation="../bin/CommonElement.xsd"/>
  <xs:include schemaLocation="../bin/CommonType.xsd"/>
  <xs:element name="Toolkit">
    <xs:annotation>
      <xs:documentation>定义相对固定，比较简单的代码表，用Xml来配置来实现。配置在Xml/Decoder目录下，文件名必须以*CodeData.xml的形式存在</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="CodeData">
          <xs:annotation>
            <xs:documentation>定义一个简单的Xml配置代码表</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="tk:Row" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>一条代码记录</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="tk:RegItem"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" use="required" fixed="5.0">
        <xs:annotation>
          <xs:documentation>版本号</xs:documentation>
          <xs:documentation>!</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Row">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Value" type="xs:token">
          <xs:annotation>
            <xs:documentation>代码值，要求在此配置中保证唯一</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="Name" type="tk:MultiLanguageType">
          <xs:annotation>
            <xs:documentation>代码显示的名称，支持多语言配置</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== madiantech/tkcore/CoreWebTest/TestWeb/Xml/Decoder/Workflow/WorkflowCodeData.xml
<?xml version="1.0" encoding="utf-8"?>
<tk:Toolkit version="5.0" xsi:schemaLocation="http://www.qdocuments.net ..\..\schema\v5\CodeData.xsd" xmlns:tk="http://www.qdocuments.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <tk:CodeData RegName="ApproveOperator" Author="YJC" CreateDate="2018-04-04" Description="审核操作代码表">
    <tk:Row>
      <tk:Value>1</tk:Value>
      <tk:Name>
        <tk:Content>同意</tk:Content>
      </tk:Name>
    </tk:Row>
    <tk:Row>
      <tk:Value>0</tk:Value>
      <tk:Name>
        <tk:Content>不同意</tk:Content>
      </tk:Name>
    </tk:Row>
  </tk:CodeData>
</tk:Toolkit>
