=== madiantech/tkcore/CoreWebTest/TestWeb/Xml/schema/v5/WfCreator.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by cjy (baison) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tk="http://www.qdocuments.net" targetNamespace="http://www.qdocuments.net" elementFormDefault="qualified">
  <xs:include schemaLocation="../bin/CommonElement.xsd"/>
  <xs:include schemaLocation="../bin/CommonType.xsd"/>
  <xs:include schemaLocation="SubItems/WfCommon.xsd"/>
  <xs:complexType name="BaseWorkflowContentType">
    <xs:sequence>
      <xs:element name="Resolver" type="tk:ResolverType">
        <xs:annotation>
          <xs:documentation>获得数据的TableResolver</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Record" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>相关的记录</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Key" maxOccurs="unbounded">
              <xs:annotation>
                <xs:documentation>获取记录的字段值</xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:attribute name="NickName" type="xs:Name" use="required">
                  <xs:annotation>
                    <xs:documentation>表字段昵称</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="ParamName" type="xs:Name" use="required">
                  <xs:annotation>
                    <xs:documentation>外部接入的参数名称，通过此名称可以取到相应的值</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Toolkit">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tk:Creator"/>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" use="required" fixed="2.0"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Creator">
    <xs:annotation>
      <xs:documentation>工作流创建器</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="WorkflowName" type="xs:string">
          <xs:annotation>
            <xs:documentation>工作流名称，Evaluate表达式</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="Content" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>工作流数据内容</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:complexContent>
              <xs:extension base="tk:BaseWorkflowContentType">
                <xs:sequence>
                  <xs:element name="HistoryResolver" type="tk:ResolverType" minOccurs="0"/>
                  <xs:element name="FilterSql" type="xs:string" minOccurs="0">
                    <xs:annotation>
                      <xs:documentation>过滤条件，是Evaluator表达式。传入Source，即当前的Source对象</xs:documentation>
                    </xs:annotation>
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="IsMain" type="xs:boolean" default="false">
                  <xs:annotation>
                    <xs:documentation>是否是主表，默认为false</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="OrderBy" type="xs:string">
                  <xs:annotation>
                    <xs:documentation>排序方式，需要添加关键字ORDER BY</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="HistoryMethod">
                  <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                      <xs:enumeration value="None"/>
                      <xs:enumeration value="Perhaps"/>
                      <xs:enumeration value="History"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attributeGroup ref="tk:RegItem"/>
      <xs:attribute name="FillMode" type="tk:_tk_FillMode" default="None">
        <xs:annotation>
          <xs:documentation>填充模式，默认为None</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== madiantech/tkcore/CoreWebTest/TestWeb/Xml/Workflow/CounterSign/CounterSignCreator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 (http://www.altova.com)-->
<tk:Toolkit version="2.0" xsi:schemaLocation="http://www.qdocuments.net ../../schema/v5/WfCreator.xsd" xmlns:tk="http://www.qdocuments.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <tk:Creator RegName="CounterSignBegin">
    <tk:WorkflowName>'会签 - ' + DataSetExtension.GetString(row, 'WfTitle')</tk:WorkflowName>
    <tk:Content IsMain="true">
      <tk:Resolver>
        <tk:RegResolver>CounterSign</tk:RegResolver>
      </tk:Resolver>
      <tk:Record>
        <tk:Key ParamName="Id" NickName="Id"/>
      </tk:Record>
    </tk:Content>
    <tk:Content>
      <tk:Resolver>
        <tk:DataXmlResolver DataXml="TestWf/Requirement.xml" AutoTrackField="true" AutoUpdateKey="true"/>
      </tk:Resolver>
      <tk:Record>
        <tk:Key ParamName="MainId" NickName="Id"/>
      </tk:Record>
    </tk:Content>
    <tk:Content>
      <tk:Resolver>
        <tk:RegResolver>ApproveHistory</tk:RegResolver>
      </tk:Resolver>
      <tk:Record>
        <tk:Key ParamName="WfId" NickName="WorkflowId"/>
      </tk:Record>
    </tk:Content>
  </tk:Creator>
</tk:Toolkit>

=== madiantech/tkcore/CoreWebTest/TestWeb/Xml/Workflow/CounterSign/NormalCreator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 (http://www.altova.com)-->
<tk:Toolkit version="2.0" xsi:schemaLocation="http://www.qdocuments.net ../../schema/v5/WfCreator.xsd" xmlns:tk="http://www.qdocuments.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <tk:Creator RegName="TestBegin2">
    <tk:WorkflowName>DataSetExtension.GetString(row, 'BillNo')</tk:WorkflowName>
    <tk:Content IsMain="true">
      <tk:Resolver>
        <tk:DataXmlResolver DataXml="TestWf/Requirement.xml" AutoTrackField="true" AutoUpdateKey="true"/>
      </tk:Resolver>
      <tk:Record>
        <tk:Key ParamName="Id" NickName="Id"/>
      </tk:Record>
    </tk:Content>
  </tk:Creator>
</tk:Toolkit>
