=== madiantech/tkcore/CoreTest/TestConsoleApp/Xml/schema/v5/EasySearch.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by cjy (baison) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tk="http://www.qdocuments.net" targetNamespace="http://www.qdocuments.net" elementFormDefault="qualified">
  <xs:include schemaLocation="../bin/CommonElement.xsd"/>
  <xs:include schemaLocation="../bin/CommonType.xsd"/>
  <xs:include schemaLocation="SubItems/Cache.xsd"/>
  <xs:include schemaLocation="SubItems/DataRight.xsd"/>
  <xs:include schemaLocation="SubItems/Tree.xsd"/>
  <xs:element name="Toolkit">
    <xs:complexType>
      <xs:group ref="tk:EasySearchGroup" maxOccurs="unbounded"/>
      <xs:attribute name="version" type="xs:string" use="required" fixed="5.0"/>
    </xs:complexType>
  </xs:element>
  <xs:group name="EasySearchGroup">
    <xs:choice>
      <xs:element ref="tk:Tk5EasySearch"/>
      <xs:element ref="tk:Tk5CodeTableEasySearch"/>
      <xs:element ref="tk:Tk5LevelCodeTableEasySearch"/>
      <xs:element ref="tk:Tk5Level0CodeTableEasySearch"/>
      <xs:element ref="tk:Tk5TreeEasySearch"/>
      <xs:any namespace="##other" processContents="lax" maxOccurs="unbounded"/>
    </xs:choice>
  </xs:group>
  <xs:attributeGroup name="CodeTableAttrGroup">
    <xs:attribute name="Context" type="xs:Name">
      <xs:annotation>
        <xs:documentation>数据库连接的名称，不写使用调用的DbContext</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="OrderBy" type="xs:string">
      <xs:annotation>
        <xs:documentation>排序，如果填写需要加上order by</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NameExpression" type="xs:string">
      <xs:annotation>
        <xs:documentation>显示内容，默认为{Name}，字段名需要用{}包围。支持以下格式：1）例：{Name`格式[0]}，以`为界，前面为字段名，后面是Format格式。如果字段为空，整个内容输出为空。Format中的{0}用[0]代替</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="DisplayNameExpression" type="xs:string">
      <xs:annotation>
        <xs:documentation>在下拉列表和对话框中显示的内容，格式和NameExpression一致。如果不配置，将采用NameExpression的定义</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="Tk5EasySearch" type="tk:Tk5EasySearchType">
    <xs:annotation>
      <xs:documentation>支持Tk5的DataXml的EasySearch配置</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="Tk5CodeTableEasySearch" type="tk:CodeTableEasySearchType">
    <xs:annotation>
      <xs:documentation>支持Tk5的标准代码表的EasySearch配置</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="Tk5LevelCodeTableEasySearch" type="tk:LevelCodeTableEasySearchType">
    <xs:annotation>
      <xs:documentation>Tk5以Level模式的树形标准代码表的EasySearch配置</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="Tk5Level0CodeTableEasySearch" type="tk:LevelCodeTableEasySearchType">
    <xs:annotation>
      <xs:documentation>Tk5以Level0模式的树形标准代码表的EasySearch配置</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="Tk5TreeEasySearch" type="tk:Tk5EasySearchType">
    <xs:annotation>
      <xs:documentation>支持Tk5的DataXml的TreeEasySearch配置</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="CodeTableEasySearchType">
    <xs:attribute name="TableName" type="xs:Name" use="required">
      <xs:annotation>
        <xs:documentation>标准代码表的表名，必须有五个标准字段</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attributeGroup ref="tk:RegItem"/>
    <xs:attributeGroup ref="tk:CodeTableAttrGroup"/>
  </xs:complexType>
  <xs:complexType name="LevelCodeTableEasySearchType">
    <xs:complexContent>
      <xs:extension base="tk:CodeTableEasySearchType">
        <xs:sequence>
          <xs:element name="Level" type="xs:unsignedInt" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>配置每级Level所占的代码的位数</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Tk5EasySearchType">
    <xs:sequence>
      <xs:element name="FilterSql" type="tk:MarcoConfigItem" minOccurs="0">
        <xs:annotation>
          <xs:documentation>过滤Sql</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CacheDependency" type="tk:DependencyType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>缓存依赖</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DataRight" type="tk:DataRightType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>数据权限配置，可以对数据进行相应的过滤</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="SearchMethod" type="xs:Name" minOccurs="0">
        <xs:annotation>
          <xs:documentation>自定义搜索方法的插件名</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="DataXml" type="xs:anyURI" use="required">
      <xs:annotation>
        <xs:documentation>Toolkit 5格式的DataXml，要求支持NameField</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attributeGroup ref="tk:RegItem"/>
    <xs:attributeGroup ref="tk:CodeTableAttrGroup"/>
    <xs:attribute name="TopCount" type="xs:unsignedInt">
      <xs:annotation>
        <xs:documentation>配置一次最多显示的搜索项，默认为15</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="PyField" type="xs:Name">
      <xs:annotation>
        <xs:documentation>如果有存储Name的拼音简写字段，就配置该字段。否则将模拟生成SQL对Name字段进行查询</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="IdField" type="xs:Name">
      <xs:annotation>
        <xs:documentation>如果配置，将重载DataXml中的Id字段</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="NameField" type="xs:Name">
      <xs:annotation>
        <xs:documentation>如果配置，将重载DataXml中的Name字段</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
</xs:schema>

=== madiantech/tkcore/CoreWebTest/TestWeb/Xml/Decoder/UserManager/UserEasySearch.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Chen Jiangyong (Baison) -->
<tk:Toolkit version="5.0" xsi:schemaLocation="http://www.qdocuments.net ..\..\schema\v5\EasySearch.xsd" xmlns:tk="http://www.qdocuments.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <tk:Tk5EasySearch DataXml="UserManager/User.xml" RegName="USER" Author="YJC" CreateDate="2014-07-12" Description="用户"/>
  <tk:Tk5EasySearch DataXml="UserManager/Part.xml" RegName="PART" Author="YJC" CreateDate="2014-07-12" Description="角色"/>
  <tk:Tk5TreeEasySearch DataXml="UserManager/Organization.xml" RegName="ORG" Author="YJC" CreateDate="2014-07-12" Description="机构"/>
  <tk:Tk5TreeEasySearch  DataXml="UserManager/Function.xml" RegName="FUNCTION" Author="YJC" CreateDate="2014-07-12" Description="菜单"/>
  <tk:Tk5Level0CodeTableEasySearch TableName="CD_SX" RegName="SX" Author="YJC" CreateDate="2014-07-12" Description="地区" DisplayNameExpression="{Value} - {Name}" >
    <tk:Level>2</tk:Level>
    <tk:Level>2</tk:Level>
    <tk:Level>2</tk:Level>
  </tk:Tk5Level0CodeTableEasySearch>
</tk:Toolkit>
